default:
  image: maven:3.8.8-eclipse-temurin-21
  services:
    - docker:dind

stages:
  - detect-changes
  - build-proto
  - build
  - deploy

variables:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: $DOCKERHUB_USERNAME
  DOCKER_PASSWORD: $DOCKER_PASSWORD
  IMAGE_NAME: sop-rw
  BASE_BRANCH: develop
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
  DOCKER_BUILDKIT: "1"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  AVAILABLE_SERVICES: "role-access-control-service user-management-service discovery-service gateway-service analytics-insights-service audit-compliance-tracking-service compliance-reporting-service notification-service sop-content-service sop-recommendation-service sop-workflow-service version-control-service"
  DOCKER_CLEANUP_ENABLED: "true"
  DEPLOYMENT_TIMEOUT: "300"
  HEALTH_CHECK_RETRIES: "30"
  HEALTH_CHECK_INTERVAL: "10"

cache:
  paths:
    - .m2/repository/
  key: ${CI_COMMIT_REF_SLUG}

.cleanup_script: &cleanup_script |
  if [ "$DOCKER_CLEANUP_ENABLED" = "true" ]; then
    echo "Cleaning up Docker resources..."
    docker system prune -f
  fi

detect-changes:
  stage: detect-changes
  script:
    - echo "Fetching the latest base branch history..."
    - git fetch origin $BASE_BRANCH --prune
    - |
      echo "Identifying changes..."
      
      if [ "$CI_COMMIT_BRANCH" = "develop" ]; then
        echo "On develop branch - including all services"
        export CHANGED_SERVICES="$AVAILABLE_SERVICES"
      else
        lastMergeCommit=$(git log --merges --pretty=format:'%H' -n 1 origin/$BASE_BRANCH || true)
      
        if [ -z "$lastMergeCommit" ]; then
          echo "No merge commits found, using the last commit instead..."
          lastMergeCommit=$(git log --pretty=format:'%H' -n 1 origin/$BASE_BRANCH)
        fi
      
        if [ -z "$lastMergeCommit" ]; then
          echo "Failed to identify any commits on branch '$BASE_BRANCH'."
          exit 1
        fi
      
        echo "Reference commit SHA: $lastMergeCommit"
      
        detectedChanges=$(git diff --name-only $lastMergeCommit...HEAD | sort -u)
        if [ -z "$detectedChanges" ]; then
          echo "No changes detected in the repository."
          echo "export CHANGED_SERVICES=\"\"" > changes
          exit 0
        fi
      
        servicesInChanges=()
        for change in $detectedChanges; do
          service=$(echo $change | cut -d '/' -f 1)
          if [[ " $AVAILABLE_SERVICES " == *" $service "* ]]; then
            servicesInChanges+=($service)
          fi
        done
      
        if [ ${#servicesInChanges[@]} -gt 0 ]; then
          servicesInChanges+=("discovery-service" "gateway-service")
        fi
      
        export CHANGED_SERVICES=$(echo "${servicesInChanges[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')
      fi
    - echo "Services to process:" $CHANGED_SERVICES
    - echo "export CHANGED_SERVICES=\"$CHANGED_SERVICES\"" > changes
    - chmod +x changes
  artifacts:
    paths:
      - changes
    expire_in: 1h
    when: always

build-proto:
  stage: build-proto
  script:
    - cd proto || exit 1
    - mvn clean package -DskipTests
    - mkdir -p ../libs
    - cp target/*.jar ../libs/
    - cd ..
  artifacts:
    paths:
      - libs
    expire_in: 1h
    when: always

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      command: [ "--tls=false" ]
  needs:
    - job: build-proto
      artifacts: true
    - job: detect-changes
      artifacts: true
  before_script:
    - apk add --no-cache bash
    - |
      if [ ! -f "changes" ]; then
        echo "No changes file found"
        echo "export CHANGED_SERVICES=\"\"" > changes
      fi
    - chmod +x changes
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - *cleanup_script
    - source changes || echo "Failed to source changes file"
    - |
      if [ -z "$CHANGED_SERVICES" ]; then
        echo "No services to build"
        exit 0
      fi
      
      for SERVICE in $CHANGED_SERVICES; do
        if [[ "${SERVICE}" != "proto" ]]; then
          echo "=== Starting build for ${SERVICE} ==="
      
          if [ ! -d "${SERVICE}" ] || [ ! -f "${SERVICE}/Dockerfile" ]; then
            echo "Error: Invalid service directory or missing Dockerfile for ${SERVICE}"
            exit 1
          fi
      
          mkdir -p "${SERVICE}/libs/"
          cp libs/*.jar "${SERVICE}/libs/" 2>/dev/null || true
      
          CURRENT_DIR=$(pwd)
          cd "${SERVICE}" || exit 1
      
          echo "Building image ${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${IMAGE_NAME}:${SERVICE}-latest"
          if ! docker build --no-cache -t "${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${IMAGE_NAME}:${SERVICE}-latest" .; then
            echo "Error: Docker build failed for ${SERVICE}"
            cd "${CURRENT_DIR}"
            exit 1
          fi
      
          if [ "$CI_COMMIT_BRANCH" = "develop" ]; then
            echo "Pushing image for ${SERVICE}"
            if ! docker push "${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${IMAGE_NAME}:${SERVICE}-latest"; then
              echo "Error: Failed to push image for ${SERVICE}"
              exit 1
            fi
          fi
      
          cd "${CURRENT_DIR}"
          echo "=== ${SERVICE} build complete ==="
        fi
      done
  after_script:
    - docker logout
    - *cleanup_script
  artifacts:
    paths:
      - changes
    expire_in: 1h
    when: always

deploy:
  stage: deploy
  image: alpine:latest
  needs:
    - job: build
      artifacts: true
    - job: detect-changes
      artifacts: true
  before_script:
    - apk add --no-cache openssh bash curl jq
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts 2>/dev/null
    - |
      if [ ! -f "changes" ]; then
        echo "No changes file found"
        echo "export CHANGED_SERVICES=\"\"" > changes
      fi
    - chmod +x changes
  script:
    - source changes || echo "Failed to source changes file"
    - |
      if [ -z "$CHANGED_SERVICES" ]; then
        echo "No services to deploy"
        exit 0
      fi
      
      echo "Deploying services: $CHANGED_SERVICES"
      
      # Copy deployment script and docker-compose to EC2
      ssh -i ~/.ssh/id_rsa ubuntu@$DEPLOY_SERVER "
        cd /home/projects/sop-rw || mkdir -p /home/projects/sop-rw
      
        # Set environment variables
        export DOCKER_USERNAME='$DOCKER_USERNAME'
        export DOCKER_PASSWORD='$DOCKER_PASSWORD'
        export CHANGED_SERVICES='$CHANGED_SERVICES'
      
        # Login to Docker Hub
        echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_USERNAME' --password-stdin
      
        # Deploy discovery service first if it's in the changed services
        if [[ \"$CHANGED_SERVICES\" == *\"discovery-service\"* ]]; then
          echo \"Deploying discovery-service...\"
          docker compose pull discovery-service
          docker compose up -d discovery-service
      
          # Wait for discovery service
          for i in \$(seq 1 $HEALTH_CHECK_RETRIES); do
            if docker compose ps discovery-service | grep -q \"Up\"; then
              break
            fi
            echo \"Waiting for discovery-service... Attempt \$i/$HEALTH_CHECK_RETRIES\"
            sleep $HEALTH_CHECK_INTERVAL
          done
        fi
      
        # Deploy gateway service next if it's in the changed services
        if [[ \"$CHANGED_SERVICES\" == *\"gateway-service\"* ]]; then
          echo \"Deploying gateway-service...\"
          docker compose pull gateway-service
          docker compose up -d gateway-service
      
          # Wait for gateway service
          for i in \$(seq 1 $HEALTH_CHECK_RETRIES); do
            if docker compose ps gateway-service | grep -q \"Up\"; then
              break
            fi
            echo \"Waiting for gateway-service... Attempt \$i/$HEALTH_CHECK_RETRIES\"
            sleep $HEALTH_CHECK_INTERVAL
          done
        fi
      
        # Deploy remaining services
        for SERVICE in $CHANGED_SERVICES; do
          if [[ \"\$SERVICE\" != \"proto\" && \"\$SERVICE\" != \"discovery-service\" && \"\$SERVICE\" != \"gateway-service\" ]]; then
            echo \"Deploying \$SERVICE...\"
      
            # Pull latest image
            docker compose pull \$SERVICE || { echo \"Failed to pull \$SERVICE\"; continue; }
      
            # Stop and remove existing container
            docker compose stop \$SERVICE || true
            docker compose rm -f \$SERVICE || true
      
            # Start new container
            docker compose up -d \$SERVICE
      
            # Wait for service to be healthy
            for i in \$(seq 1 $HEALTH_CHECK_RETRIES); do
              if docker compose ps \$SERVICE | grep -q \"Up\"; then
                break
              fi
              echo \"Waiting for \$SERVICE... Attempt \$i/$HEALTH_CHECK_RETRIES\"
              sleep $HEALTH_CHECK_INTERVAL
            done
          fi
        done
      
        # Final status check
        echo \"Final status of services:\"
        docker compose ps
      
        # Cleanup
        docker system prune -f
        docker logout
      "
      
      # Verify deployment
      echo "Verifying final deployment status..."
      for SERVICE in $CHANGED_SERVICES; do
        if [[ "${SERVICE}" != "proto" ]]; then
          echo "Checking ${SERVICE}..."
          if ! ssh -i ~/.ssh/id_rsa ubuntu@$DEPLOY_SERVER "cd /home/projects/sop-rw && docker compose ps ${SERVICE} | grep -q Up"; then
            echo "Service ${SERVICE} failed to start. Checking logs..."
            ssh -i ~/.ssh/id_rsa ubuntu@$DEPLOY_SERVER "cd /home/projects/sop-rw && docker compose logs ${SERVICE}"
            exit 1
          fi
          echo "${SERVICE} is running properly"
        fi
      done
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  timeout: 1 hour

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - when: never

  