default:
  image: maven:3.8.8-eclipse-temurin-21
  services:
    - docker:dind

stages:
  - detect-changes
  - build-proto
  - build
  - deploy

variables:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: $DOCKERHUB_USERNAME
  DOCKER_PASSWORD: $DOCKER_PASSWORD
  IMAGE_NAME: sop-rw
  BASE_BRANCH: develop
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
  DOCKER_BUILDKIT: "1"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  # Unified service names
  AVAILABLE_SERVICES: "role-access-control-service user-management-service discovery-service gateway-service analytics-insights-service audit-compliance-tracking-service compliance-reporting-service notification-service sop-content-service sop-recommendation-service sop-workflow-service version-control-service"
  DOCKER_CLEANUP_ENABLED: "true"
  DEPLOYMENT_TIMEOUT: "300"
  HEALTH_CHECK_RETRIES: "30"
  HEALTH_CHECK_INTERVAL: "10"

cache:
  paths:
    - .m2/repository/
  key: ${CI_COMMIT_REF_SLUG}

.cleanup_script: &cleanup_script |
  if [ "$DOCKER_CLEANUP_ENABLED" = "true" ]; then
    echo "Cleaning up Docker resources..."
    docker system prune -f
  fi

detect-changes:
  stage: detect-changes
  script:
    - |
      get_service_name() {
        local directory_name=$1
        # Map directory names to service names if needed
        case $directory_name in
          "analytics") echo "analytics-insights-service" ;;
          "audit") echo "audit-compliance-tracking-service" ;;
          "reporting") echo "compliance-reporting-service" ;;
          "recommendation") echo "sop-recommendation-service" ;;
          *) echo "$directory_name" ;;
        esac
      }
    - echo "Fetching the latest base branch history..."
    - git fetch origin $BASE_BRANCH --prune
    - |
      echo "Identifying changes..."
      
      if [ "$CI_COMMIT_BRANCH" = "develop" ]; then
        echo "On develop branch - including all services"
        export CHANGED_SERVICES="$AVAILABLE_SERVICES"
      else
        lastMergeCommit=$(git log --merges --pretty=format:'%H' -n 1 origin/$BASE_BRANCH || true)
      
        if [ -z "$lastMergeCommit" ]; then
          echo "No merge commits found, using the last commit instead..."
          lastMergeCommit=$(git log --pretty=format:'%H' -n 1 origin/$BASE_BRANCH)
        fi
      
        if [ -z "$lastMergeCommit" ]; then
          echo "Failed to identify any commits on branch '$BASE_BRANCH'."
          exit 1
        fi
      
        echo "Reference commit SHA: $lastMergeCommit"
      
        detectedChanges=$(git diff --name-only $lastMergeCommit...HEAD | sort -u)
        if [ -z "$detectedChanges" ]; then
          echo "No changes detected in the repository."
          echo "export CHANGED_SERVICES=\"\"" > changes
          exit 0
        fi
      
        servicesInChanges=()
        for change in $detectedChanges; do
          directory=$(echo $change | cut -d '/' -f 1)
          service=$(get_service_name "$directory")
          if [[ " $AVAILABLE_SERVICES " == *" $service "* ]]; then
            servicesInChanges+=($service)
          fi
        done
      
        # Always include discovery-service and gateway-service for dependent services
        if [ ${#servicesInChanges[@]} -gt 0 ]; then
          servicesInChanges+=("discovery-service" "gateway-service")
        fi
      
        export CHANGED_SERVICES=$(echo "${servicesInChanges[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')
      fi
    - echo "Services to process:" $CHANGED_SERVICES
    - echo "export CHANGED_SERVICES=\"$CHANGED_SERVICES\"" > changes
    - chmod +x changes
  artifacts:
    paths:
      - changes
    expire_in: 1h
    when: always

build-proto:
  stage: build-proto
  script:
    - cd proto || exit 1
    - mvn clean package -DskipTests
    - mkdir -p ../libs
    - cp target/*.jar ../libs/
    - cd ..
  artifacts:
    paths:
      - libs
    expire_in: 1h
    when: always

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      command: [ "--tls=false" ]
  needs:
    - job: build-proto
      artifacts: true
    - job: detect-changes
      artifacts: true
  before_script:
    - apk add --no-cache bash
    - |
      if [ ! -f "changes" ]; then
        echo "No changes file found"
        echo "export CHANGED_SERVICES=\"\"" > changes
      fi
    - chmod +x changes
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - *cleanup_script
    - source changes || echo "Failed to source changes file"
    - |
      get_service_directory() {
        local service_name=$1
        # Map service names to directory names if needed
        case $service_name in
          "analytics-insights-service") echo "analytics" ;;
          "audit-compliance-tracking-service") echo "audit" ;;
          "compliance-reporting-service") echo "reporting" ;;
          "sop-recommendation-service") echo "recommendation" ;;
          *) echo "$service_name" ;;
        esac
      }
    - |
      if [ -z "$CHANGED_SERVICES" ]; then
        echo "No services to build"
        exit 0
      fi
      
      for SERVICE in $CHANGED_SERVICES; do
        if [[ "${SERVICE}" != "proto" ]]; then
          echo "=== Starting build for ${SERVICE} ==="
      
          SERVICE_DIR=$(get_service_directory "${SERVICE}")
      
          VERSION="${CI_COMMIT_SHA}"
          if [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ]; then
            VERSION="pr-${CI_MERGE_REQUEST_IID}"
          fi
      
          if [ ! -d "${SERVICE_DIR}" ] || [ ! -f "${SERVICE_DIR}/Dockerfile" ]; then
            echo "Error: Invalid service directory or missing Dockerfile for ${SERVICE} (${SERVICE_DIR})"
            exit 1
          fi
      
          mkdir -p "${SERVICE_DIR}/libs/"
          cp libs/*.jar "${SERVICE_DIR}/libs/" 2>/dev/null || true
      
          CURRENT_DIR=$(pwd)
          cd "${SERVICE_DIR}" || exit 1
      
          echo "Building image ${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${IMAGE_NAME}:${SERVICE}-${VERSION}"
          if ! docker build --no-cache -t "${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${IMAGE_NAME}:${SERVICE}-${VERSION}" .; then
            echo "Error: Docker build failed for ${SERVICE}"
            cd "${CURRENT_DIR}"
            exit 1
          fi
      
          if [ "$CI_COMMIT_BRANCH" = "develop" ]; then
            echo "Tagging and pushing images for ${SERVICE}"
            docker tag "${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${IMAGE_NAME}:${SERVICE}-${VERSION}" \
                      "${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${IMAGE_NAME}:${SERVICE}-latest"
      
            if ! docker push "${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${IMAGE_NAME}:${SERVICE}-${VERSION}"; then
              echo "Error: Failed to push version-tagged image for ${SERVICE}"
              exit 1
            fi
      
            if ! docker push "${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${IMAGE_NAME}:${SERVICE}-latest"; then
              echo "Error: Failed to push latest image for ${SERVICE}"
              exit 1
            fi
          fi
      
          cd "${CURRENT_DIR}"
          echo "=== ${SERVICE} build complete ==="
        fi
      done
  after_script:
    - docker logout
    - *cleanup_script
  artifacts:
    paths:
      - changes
    expire_in: 1h
    when: always

deploy:
  stage: deploy
  image: alpine:latest
  needs:
    - job: build
      artifacts: true
    - job: detect-changes
      artifacts: true
  before_script:
    - apk add --no-cache openssh bash curl
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts 2>/dev/null
    - |
      if [ ! -f "changes" ]; then
        echo "No changes file found"
        echo "export CHANGED_SERVICES=\"\"" > changes
      fi
    - chmod +x changes
  script:
    - source changes || echo "Failed to source changes file"
    - |
      if [ -z "$CHANGED_SERVICES" ]; then
        echo "No services to deploy"
        exit 0
      fi
      
      echo "Deploying services: $CHANGED_SERVICES"
      ssh -i ~/.ssh/id_rsa ubuntu@$DEPLOY_SERVER "
        cd /home/projects/sop-rw || exit 1
      
        echo 'Starting deployment process...'
        echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_USERNAME' --password-stdin
      
        echo 'Cleaning up unused Docker resources...'
        docker system prune -af
      
        # First, deploy discovery service if it's in the list
        if [[ \"$CHANGED_SERVICES\" == *\"discovery-service\"* ]]; then
          echo \"=== Deploying discovery-service first ===\"
          docker compose pull discovery-service
          docker compose up -d discovery-service
      
          # Wait for discovery service to be healthy
          echo \"Waiting for discovery-service to be ready...\"
          for i in \$(seq 1 30); do
            if docker compose ps discovery-service | grep -q \"Up\"; then
              break
            fi
            echo \"Attempt \$i/30: discovery-service not ready yet, waiting...\"
            sleep 10
          done
        fi
      
        # Next, deploy gateway service if it's in the list
        if [[ \"$CHANGED_SERVICES\" == *\"gateway-service\"* ]]; then
          echo \"=== Deploying gateway-service ===\"
          docker compose pull gateway-service
          docker compose up -d gateway-service
      
          # Wait for gateway service to be ready
          echo \"Waiting for gateway-service to be ready...\"
          for i in \$(seq 1 30); do
            if docker compose ps gateway-service | grep -q \"Up\"; then
              break
            fi
            echo \"Attempt \$i/30: gateway-service not ready yet, waiting...\"
            sleep 10
          done
        fi
      
        # Deploy the rest of the services
        for SERVICE in $CHANGED_SERVICES; do
          if [[ \"\${SERVICE}\" != \"proto\" && \"\${SERVICE}\" != \"discovery-service\" && \"\${SERVICE}\" != \"gateway-service\" ]]; then
            echo \"=== Deploying \${SERVICE} ===\"
      
            echo \"Pulling latest image...\"
            if ! docker compose pull \${SERVICE}; then
              echo \"Error: Failed to pull image for \${SERVICE}\"
              continue
            fi
      
            echo \"Stopping and removing old container...\"
            docker compose stop \${SERVICE} || true
            docker compose rm -f \${SERVICE} || true
      
            echo \"Starting service...\"
            if ! docker compose up -d \${SERVICE}; then
              echo \"Error: Failed to start \${SERVICE}\"
              continue
            fi
      
            # Wait for service to be ready
            echo \"Waiting for \${SERVICE} to be ready...\"
            for i in \$(seq 1 30); do
              if docker compose ps \${SERVICE} | grep -q \"Up\"; then
                break
              fi
              echo \"Attempt \$i/30: \${SERVICE} not ready yet, waiting...\"
              sleep 10
            done
      
            echo \"=== \${SERVICE} deployment complete ===\"
          fi
        done
      
        echo 'Checking final service status...'
        docker compose ps
      
        echo 'Deployment process completed'
        docker logout"
      
      echo "Verifying deployment..."
      sleep 30
      
      for SERVICE in $CHANGED_SERVICES; do
        if [[ "${SERVICE}" != "proto" ]]; then
          echo "Checking ${SERVICE}..."
          if ! ssh -i ~/.ssh/id_rsa ubuntu@$DEPLOY_SERVER "docker compose ps ${SERVICE} | grep -q Up"; then
            echo "Error: ${SERVICE} is not running properly"
            exit 1
          fi
        fi
      done
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  timeout: 1 hour

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - when: never