services:
  discovery-service:
    image: isaruratech/sop-rw:discovery-service
    container_name: discovery-service
    env_file:
      - .env
    ports:
      - "8761:8761"
    networks:
      - sop-network

  gateway-service:
    image: isaruratech/sop-rw:gateway-service
    container_name: gateway-service
    env_file:
      - .env
    ports:
      - "9091:8085"
    networks:
      - sop-network
    depends_on:
      - discovery-service

  user-management-service:
    image: isaruratech/sop-rw:user-management-service
    container_name: user-management-service
    env_file:
      - .env
    ports:
      - "6075:8081"
    networks:
      - sop-network
    depends_on:
      - discovery-service
      - postgres

  analytics-insights-service:
    image: isaruratech/sop-rw:analytics-insights-service
    container_name: analytics-service
    env_file:
      - .env
    ports:
      - "6067:8082"
    networks:
      - sop-network
    depends_on:
      - discovery-service
      - postgres

  audit-compliance-tracking-service:
    image: isaruratech/sop-rw:audit-compliance-tracking-service
    container_name: audit-service
    env_file:
      - .env
    ports:
      - "8088:8083"
    networks:
      - sop-network
    depends_on:
      - discovery-service
      - postgres

  compliance-reporting-service:
    image: isaruratech/sop-rw:compliance-reporting-service
    container_name: reporting-service
    env_file:
      - .env
    ports:
      - "8084:8084"
    networks:
      - sop-network
    depends_on:
      - discovery-service
      - postgres

  notification-service:
    image: isaruratech/sop-rw:notification-service
    container_name: notification-service
    env_file:
      - .env
    ports:
      - "8085:8085"
    networks:
      - sop-network
    depends_on:
      - discovery-service
      - redis

  sop-content-service:
    image: isaruratech/sop-rw:sop-content-service
    container_name: sop-content-service
    env_file:
      - .env
    ports:
      - "8086:8086"
    networks:
      - sop-network
    depends_on:
      - discovery-service
      - postgres

  sop-recommendation-service:
    image: isaruratech/sop-rw:sop-recommendation-service
    container_name: recommendation-service
    env_file:
      - .env
    ports:
      - "8087:8087"
    networks:
      - sop-network
    depends_on:
      - discovery-service
      - redis

  sop-workflow-service:
    image: isaruratech/sop-rw:sop-workflow-service
    container_name: workflow-service
    env_file:
      - .env
    ports:
      - "6063:8088"
    networks:
      - sop-network
    depends_on:
      - discovery-service
      - postgres

  version-control-service:
    image: isaruratech/sop-rw:version-control-service
    container_name: version-control-service
    env_file:
      - .env
    ports:
      - "5060:8089"
    networks:
      - sop-network
    depends_on:
      - discovery-service
      - postgres

  role-access-control-service:
    image: isaruratech/sop-rw:role-access-control-service
    container_name: role-access-service
    env_file:
      - .env
    ports:
      - "7079:8090"
    networks:
      - sop-network
    depends_on:
      - discovery-service
      - postgres

  zookeeper:
    image: apache/zookeeper:latest
    container_name: zookeeper
    env_file:
      - .env
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - sop-network
    volumes:
      - zookeeper_data:/data
      - zookeeper_log:/datalog

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    env_file:
      - .env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,INTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    ports:
      - "9092:9092"
    networks:
      - sop-network
    volumes:
      - kafka_data:/kafka
    depends_on:
      - zookeeper

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sopdb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sop-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sop-network

networks:
  sop-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  kafka_data:
  zookeeper_data:
  zookeeper_log: