spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: sop-workflow-service
          uri: lb://sop-workflow-service
          predicates:
            - Path=/workflow/**
          filters:
            - name: AuthFilter
            - name: RewritePath
              args:
                regexp: /workflow/(?<remaining>.*)
                replacement: /${remaining}
            - name: RewritePath
              args:
                regexp: /workflow/v3/api-docs
                replacement: /v3/api-docs
            - name: RewritePath
              args:
                regexp: /workflow/swagger-ui/(?<segment>.*)
                replacement: /swagger-ui/${segment}

        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/users/**
          filters:
            - name: AuthFilter
            - name: RewritePath
              args:
                regexp: /users/(?<remaining>.*)
                replacement: /${remaining}
            - name: RewritePath
              args:
                regexp: /users/v3/api-docs
                replacement: /v3/api-docs
            - name: RewritePath
              args:
                regexp: /users/swagger-ui/(?<segment>.*)
                replacement: /swagger-ui/${segment}

        - id: analytics-insights-service
          uri: lb://analytics-insights-service
          predicates:
            - Path=/analytics/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - name: AuthFilter
            - name: RewritePath
              args:
                regexp: /analytics/(?<remaining>.*)
                replacement: /${remaining}
            - name: RewritePath
              args:
                regexp: /analytics/v3/api-docs
                replacement: /v3/api-docs
            - name: RewritePath
              args:
                regexp: /analytics/swagger-ui/(?<segment>.*)
                replacement: /swagger-ui/${segment}

        - id: audit-compliance-tracking-service
          uri: lb://audit-compliance-tracking-service
          predicates:
            - Path=/audit/**
          filters:
            - name: AuthFilter
            - name: RewritePath
              args:
                regexp: /audit/(?<remaining>.*)
                replacement: /${remaining}
            - name: RewritePath
              args:
                regexp: /audit/v3/api-docs
                replacement: /v3/api-docs
            - name: RewritePath
              args:
                regexp: /audit/swagger-ui/(?<segment>.*)
                replacement: /swagger-ui/${segment}

        - id: compliance-reporting-service
          uri: lb://compliance-reporting-service
          predicates:
            - Path=/compliance/**
          filters:
            - name: AuthFilter
            - name: RewritePath
              args:
                regexp: /compliance/(?<remaining>.*)
                replacement: /${remaining}
            - name: RewritePath
              args:
                regexp: /compliance/v3/api-docs
                replacement: /v3/api-docs
            - name: RewritePath
              args:
                regexp: /compliance/swagger-ui/(?<segment>.*)
                replacement: /swagger-ui/${segment}

        - id: discovery-service
          uri: lb://discovery-service
          predicates:
            - Path=/discovery/**
          filters:
            - name: RewritePath
              args:
                regexp: /discovery/(?<remaining>.*)
                replacement: /${remaining}
            - name: RewritePath
              args:
                regexp: /discovery/v3/api-docs
                replacement: /v3/api-docs
            - name: RewritePath
              args:
                regexp: /discovery/swagger-ui/(?<segment>.*)
                replacement: /swagger-ui/${segment}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - name: AuthFilter
            - name: RewritePath
              args:
                regexp: /notifications/(?<remaining>.*)
                replacement: /${remaining}
            - name: RewritePath
              args:
                regexp: /notifications/v3/api-docs
                replacement: /v3/api-docs
            - name: RewritePath
              args:
                regexp: /notifications/swagger-ui/(?<segment>.*)
                replacement: /swagger-ui/${segment}

        - id: role-access-control-service
          uri: lb://role-access-control-service
          predicates:
            - Path=/access/**
          filters:
            - name: AuthFilter
            - name: RewritePath
              args:
                regexp: /access/(?<remaining>.*)
                replacement: /${remaining}
            - name: RewritePath
              args:
                regexp: /access/v3/api-docs
                replacement: /v3/api-docs
            - name: RewritePath
              args:
                regexp: /access/swagger-ui/(?<segment>.*)
                replacement: /swagger-ui/${segment}

        - id: sop-content-service
          uri: lb://sop-content-service
          predicates:
            - Path=/content/**
          filters:
            - name: AuthFilter
            - name: RewritePath
              args:
                regexp: /content/(?<remaining>.*)
                replacement: /${remaining}
            - name: RewritePath
              args:
                regexp: /content/v3/api-docs
                replacement: /v3/api-docs
            - name: RewritePath
              args:
                regexp: /content/swagger-ui/(?<segment>.*)
                replacement: /swagger-ui/${segment}

        - id: sop-recommendation-service
          uri: lb://sop-recommendation-service
          predicates:
            - Path=/recommendations/**
          filters:
            - name: AuthFilter
            - name: RewritePath
              args:
                regexp: /recommendations/(?<remaining>.*)
                replacement: /${remaining}
            - name: RewritePath
              args:
                regexp: /recommendations/v3/api-docs
                replacement: /v3/api-docs
            - name: RewritePath
              args:
                regexp: /recommendations/swagger-ui/(?<segment>.*)
                replacement: /swagger-ui/${segment}

        - id: version-control-service
          uri: lb://version-control-service
          predicates:
            - Path=/versions/**
          filters:
            - name: AuthFilter
            - name: RewritePath
              args:
                regexp: /versions/(?<remaining>.*)
                replacement: /${remaining}
            - name: RewritePath
              args:
                regexp: /versions/v3/api-docs
                replacement: /v3/api-docs
            - name: RewritePath
              args:
                regexp: /versions/swagger-ui/(?<segment>.*)
                replacement: /swagger-ui/${segment}

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
            maxAge: 3600

      httpclient:
        connect-timeout: 30000
        response-timeout: 30000

      x-forwarded:
        enabled: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    filter: true
    show-extensions: true
    show-common-extensions: true
    urls:
      - name: SOP Workflow Service
        url: /workflow/v3/api-docs
      - name: User Management Service
        url: /users/v3/api-docs
      - name: Analytics Insights Service
        url: /analytics/v3/api-docs
      - name: Audit Compliance Tracking Service
        url: /audit/v3/api-docs
      - name: Compliance Reporting Service
        url: /compliance/v3/api-docs
      - name: Discovery Service
        url: /discovery/v3/api-docs
      - name: Notification Service
        url: /notifications/v3/api-docs
      - name: Role Access Control Service
        url: /access/v3/api-docs
      - name: SOP Content Service
        url: /content/v3/api-docs
      - name: SOP Recommendation Service
        url: /recommendations/v3/api-docs
      - name: Version Control Service
        url: /versions/v3/api-docs
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 3600000000
  reset:
    expiration: 900000